// Code generated by "stringer -type=form"; DO NOT EDIT.

package decimal

import "fmt"

const (
	_form_name_0 = "zerofinite"
	_form_name_1 = "nan"
	_form_name_2 = "snan"
	_form_name_3 = "qnan"
	_form_name_4 = "inf"
	_form_name_5 = "pinf"
	_form_name_6 = "ninf"
)

var (
	_form_index_0 = [...]uint8{0, 4, 10}
	_form_index_1 = [...]uint8{0, 3}
	_form_index_2 = [...]uint8{0, 4}
	_form_index_3 = [...]uint8{0, 4}
	_form_index_4 = [...]uint8{0, 3}
	_form_index_5 = [...]uint8{0, 4}
	_form_index_6 = [...]uint8{0, 4}
)

func (i form) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _form_name_0[_form_index_0[i]:_form_index_0[i+1]]
	case i == 4:
		return _form_name_1
	case i == 12:
		return _form_name_2
	case i == 20:
		return _form_name_3
	case i == 32:
		return _form_name_4
	case i == 96:
		return _form_name_5
	case i == 160:
		return _form_name_6
	default:
		return fmt.Sprintf("form(%d)", i)
	}
}
