// Code generated by "stringer -type=form"; DO NOT EDIT

package decimal

import "fmt"

const (
	_form_name_0 = "zero"
	_form_name_1 = "finite"
	_form_name_2 = "inf"
	_form_name_3 = "pinf"
	_form_name_4 = "ninf"
)

var (
	_form_index_0 = [...]uint8{0, 4}
	_form_index_1 = [...]uint8{0, 6}
	_form_index_2 = [...]uint8{0, 3}
	_form_index_3 = [...]uint8{0, 4}
	_form_index_4 = [...]uint8{0, 4}
)

func (i form) String() string {
	switch {
	case i == 0:
		return _form_name_0
	case i == 2:
		return _form_name_1
	case i == 4:
		return _form_name_2
	case i == 12:
		return _form_name_3
	case i == 20:
		return _form_name_4
	default:
		return fmt.Sprintf("form(%d)", i)
	}
}
