// Code generated by "stringer -type RoundingMode"; DO NOT EDIT

package decimal

import "fmt"

const _RoundingMode_name = "HalfEvenAwayFromZeroToZeroPositiveInfNegativeInfHalfUpHalfDownUnneeded"

var _RoundingMode_index = [...]uint8{0, 8, 20, 26, 37, 48, 54, 62, 70}

func (i RoundingMode) String() string {
	if i >= RoundingMode(len(_RoundingMode_index)-1) {
		return fmt.Sprintf("RoundingMode(%d)", i)
	}
	return _RoundingMode_name[_RoundingMode_index[i]:_RoundingMode_index[i+1]]
}
