// Code generated by "stringer -type=RoundingMode"; DO NOT EDIT.

package dectest

import "strconv"

const _RoundingMode_name = "CeilingDownFloorHalfDownHalfEvenHalfUpUpZeroFiveUp"

var _RoundingMode_index = [...]uint8{0, 7, 11, 16, 24, 32, 38, 40, 50}

func (i RoundingMode) String() string {
	if i < 0 || i >= RoundingMode(len(_RoundingMode_index)-1) {
		return "RoundingMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RoundingMode_name[_RoundingMode_index[i]:_RoundingMode_index[i+1]]
}
